# Generated by Django 2.0.3 on 2020-11-02 08:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_for', models.CharField(choices=[('1', 'Welcome Message'), ('2', 'Chairman Message'), ('3', 'Principal Message')], max_length=1)),
                ('details', ckeditor.fields.RichTextField(blank=True)),
                ('persion_images', models.ImageField(blank=True, upload_to='images/institute')),
                ('status', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Message',
                'verbose_name_plural': 'Academic Message',
            },
        ),
        migrations.CreateModel(
            name='AcademicTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_member', models.CharField(choices=[('1', 'Management Committee '), ('2', 'Teacher'), ('4', 'Hostel Staff')], max_length=3)),
                ('member_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=60)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=40)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('member_image', models.FileField(blank=True, upload_to='images/team')),
                ('message', models.TextField(blank=True, max_length=5000)),
                ('team_order', models.IntegerField(default=0)),
                ('facebook_id', models.CharField(blank=True, max_length=100)),
                ('twitter_id', models.CharField(blank=True, max_length=100)),
                ('youtube_id', models.CharField(blank=True, max_length=100)),
                ('linkedin_id', models.CharField(blank=True, max_length=100)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Academic Member',
                'verbose_name_plural': 'Academic Teams',
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activites_name', models.CharField(max_length=60)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('details', ckeditor.fields.RichTextField()),
                ('order', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Activities',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ExamAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=60)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=50)),
                ('persion_images', models.ImageField(blank=True, upload_to='images/advisor')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exam Advice',
                'verbose_name_plural': 'Exam Advices',
            },
        ),
        migrations.CreateModel(
            name='FacilityItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('1', 'Library'), ('2', 'Hostel'), ('3', 'Lab'), ('4', 'ID Card')], max_length=1)),
                ('facility_title', models.CharField(max_length=260)),
                ('details', ckeditor.fields.RichTextField()),
                ('facility_images', models.ImageField(upload_to='images/facility_images')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facility Items',
            },
        ),
        migrations.CreateModel(
            name='GalleryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_type', models.CharField(choices=[('1', 'Video Gallery'), ('2', 'Photo Gallery')], max_length=3)),
                ('gallery_for', models.CharField(blank=True, choices=[('1', 'Hostel'), ('2', 'Library'), ('3', 'Lab'), ('5', 'ID Card')], max_length=3)),
                ('gallery_title', models.CharField(blank=True, max_length=100)),
                ('gallery_images', models.ImageField(blank=True, upload_to='images/gallery')),
                ('gallery_link', models.TextField(blank=True)),
                ('gallery_order', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Info',
                'verbose_name_plural': 'Add Gallery',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_for', models.CharField(choices=[('1', 'Academic History'), ('2', 'At a Glance'), ('3', 'Why Study')], max_length=1)),
                ('details', ckeditor.fields.RichTextField(blank=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Content',
                'verbose_name_plural': 'Home Contents',
            },
        ),
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=100)),
                ('link_url', models.CharField(blank=True, max_length=60)),
                ('order', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Important Link',
                'verbose_name_plural': 'Add Important Link',
            },
        ),
        migrations.CreateModel(
            name='JobCircular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=260)),
                ('vacancy', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('job_details', ckeditor.fields.RichTextField(blank=True)),
                ('add_date', models.DateField()),
                ('deadline_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Job Circular',
                'verbose_name_plural': 'Jobs Circular',
            },
        ),
        migrations.CreateModel(
            name='MyAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.CharField(blank=True, max_length=100)),
                ('award_year', models.CharField(blank=True, max_length=100)),
                ('for_award', models.CharField(blank=True, max_length=100)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('award_details', ckeditor.fields.RichTextField()),
                ('award_images', models.ImageField(upload_to='images/award')),
                ('status', models.BooleanField(default=True)),
                ('award_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeAndEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_or_event', models.CharField(choices=[('1', 'Notice'), ('2', 'Events')], max_length=3)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('details', ckeditor.fields.RichTextField(blank=True)),
                ('upload_images', models.ImageField(blank=True, upload_to='images/notice_event_image')),
                ('notice_file', models.FileField(blank=True, upload_to='images/notice_file')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notice Event',
                'verbose_name_plural': 'Add Notice and Event',
            },
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=160)),
                ('slugan', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('web_address', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(upload_to='images/company_info')),
                ('facebook_id', models.CharField(blank=True, max_length=200)),
                ('twitter_id', models.CharField(blank=True, max_length=200)),
                ('google_id', models.CharField(blank=True, max_length=200)),
                ('youtube_id', models.CharField(blank=True, max_length=200)),
                ('linkedin_id', models.CharField(blank=True, max_length=200)),
                ('copyright_name', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'School Profile',
                'verbose_name_plural': 'School Info',
            },
        ),
        migrations.CreateModel(
            name='SliderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_for', models.CharField(choices=[('1', 'Slider'), ('2', 'Corner Message')], max_length=3)),
                ('slider_title', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True, max_length=5000)),
                ('slider_images', models.ImageField(upload_to='images/slider')),
                ('slider_order', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slider Image',
                'verbose_name_plural': 'Slider Images',
            },
        ),
    ]
