# Generated by Django 2.0.3 on 2020-11-02 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAward',
        ),
        migrations.AlterModelOptions(
            name='jobcircular',
            options={'verbose_name': 'Job Circular', 'verbose_name_plural': 'Jobs Circulars'},
        ),
        migrations.RenameField(
            model_name='jobcircular',
            old_name='add_date',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='jobcircular',
            old_name='experience',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='jobcircular',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='jobcircular',
            name='job_details',
        ),
        migrations.RemoveField(
            model_name='jobcircular',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='jobcircular',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='jobcircular',
            name='publish_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcircular',
            name='vancancy_images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/vancancy_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcircular',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
