# Generated by Django 2.0.3 on 2020-11-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20201103_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcircular',
            name='vancancy_images',
            field=models.FileField(upload_to='images/vancancy_images'),
        ),
    ]
