# Generated by Django 2.0.3 on 2020-11-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('class_for', models.CharField(choices=[('1', 'প্রথম শ্রেণী'), ('2', 'দ্বিতীয় শ্রেণী'), ('3', 'তৃতীয় শ্রেণী'), ('4', 'চতুর্থ শ্রেণী'), ('5', 'পঞ্চম শ্রেণী'), ('6', 'ষষ্ঠ শ্রেণী'), ('7', 'সপ্তম শ্রেণী'), ('8', 'অষ্টম শ্রেণী'), ('9', 'নবম শ্রেণী')], max_length=1)),
                ('group_for', models.CharField(blank=True, choices=[('1', 'Science'), ('2', 'Business'), ('3', 'Humanities')], max_length=1, null=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admission Request',
                'verbose_name_plural': 'Admission Requests',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
