# Generated by Django 2.0.3 on 2020-11-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20201108_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ssc_roll',
        ),
        migrations.RemoveField(
            model_name='student',
            name='st_reg',
        ),
        migrations.RemoveField(
            model_name='student',
            name='st_roll',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_pass',
        ),
        migrations.AlterField(
            model_name='student',
            name='jsc_roll',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='psc_roll',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(blank=True, choices=[('1', 'General student'), ('2', 'Full fee scholarship'), ('3', 'Half fee scholarship'), ('4', 'Old student')], max_length=1),
        ),
    ]
