# Generated by Django 2.0.3 on 2020-11-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20201111_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='emp_religion',
            field=models.CharField(choices=[('1', 'Islam'), ('2', 'Christianity'), ('3', 'Hinduism'), ('4', 'Buddhism'), ('5', 'Chinese traditional religion'), ('6', 'African traditional religions')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_religion',
            field=models.CharField(choices=[('1', 'Islam'), ('2', 'Christianity'), ('3', 'Hinduism'), ('4', 'Buddhism'), ('5', 'Chinese traditional religion'), ('6', 'African traditional religions')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Religion',
        ),
    ]
