# Generated by Django 2.0.3 on 2020-11-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20201111_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelist',
            name='fitness_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fitness_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='residential_student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='transport_student',
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.DeleteModel(
            name='HealthConditionSetup',
        ),
    ]
