# Generated by Django 2.0.3 on 2020-11-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20201112_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='st_reg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='st_roll',
            field=models.IntegerField(default=0),
        ),
    ]
