# Generated by Django 2.0.3 on 2020-11-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20201112_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelist',
            name='emp_phone',
        ),
        migrations.RemoveField(
            model_name='employeelist',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='employeelist',
            name='nationality',
        ),
    ]
