# Generated by Django 2.0.3 on 2020-11-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20201121_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='resign_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
