# Generated by Django 2.0.3 on 2020-11-20 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20201121_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='resign_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
