# Generated by Django 2.0.3 on 2020-11-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20201121_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='added_by',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
