# Generated by Django 2.0.3 on 2020-11-22 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20201121_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.CharField(blank=True, choices=[('1', 'Bangla Medium'), ('2', 'English Version')], max_length=1)),
                ('status', models.BooleanField(default=1)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.ClassInfo')),
                ('group_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.GroupTypeList')),
                ('running_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Years')),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Section')),
                ('shift_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Shift')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.EmployeeList')),
            ],
            options={
                'verbose_name': 'Teacher List',
                'verbose_name_plural': 'Teacher List',
            },
        ),
    ]
