# Generated by Django 2.0.3 on 2020-11-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_teacherlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address_in_bangla',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
    ]
