# Generated by Django 2.0.3 on 2020-11-23 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20201123_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_type', models.CharField(choices=[('1', 'Written'), ('2', 'MCQ')], max_length=1)),
                ('total_mark', models.IntegerField(default=0)),
                ('pass_mark', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=1)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.ClassInfo')),
            ],
            options={
                'verbose_name': 'Mark Distribution',
                'verbose_name_plural': 'Mark Distributions',
            },
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='insert_by',
            new_name='ordering',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='update_by',
        ),
        migrations.AddField(
            model_name='markdistribution',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Subject'),
        ),
    ]
