# Generated by Django 2.0.3 on 2020-11-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='st_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Chinese traditional religion', 'Chinese traditional religion'), ('African traditional religions', 'African traditional religions')], max_length=1),
        ),
    ]
