# Generated by Django 2.0.3 on 2020-11-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20201125_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='st_blood_group',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=20),
        ),
    ]
