# Generated by Django 2.0.3 on 2020-11-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_auto_20201125_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(blank=True, choices=[('General student', 'General student'), ('Full fee scholarship', 'Full fee scholarship'), ('Half fee scholarship', 'Half fee scholarship'), ('Old student', 'Old student')], max_length=20),
        ),
    ]
